#! /bin/sh
# **************************************************************************
# Regenerate all files which are constructed by the autoconf, automake
# and libtool tool-chain.
# Note: only developers should need to use this script.
#
# Authors:
#   Lars J. Aas <larsa@sim.no>
#   Morten Eriksen <mortene@sim.no>

wd=`echo "$0" | sed -e 's,[^/]*$,,g'`
me=`echo "$0" | sed -e 's,.*/,,g'`
cd $wd
if test ! -f ./$me; then
  echo >&2 "$me: error: unexpected problem with your shell - bailing out"
  exit 1
fi

AUTOCONF_VER=2.49c     # Autoconf from CVS
AUTOMAKE_VER=1.4[abc]  # Automake from CVS
LIBTOOL_VER=1.3c       # Libtool from CVS

GUI=Qt
PROJECT=So$GUI
MACRODIR=cfg/m4

SUBPROJECTS="$MACRODIR src/Inventor/Qt/common"
SUBPROJECTNAMES="SoQtMacros SoQtCommon"

AUTOMAKE_ADD=
if test "$1" = "--clean"; then
  rm -f config.h.in \
        configure \
        stamp-h* \
        cfg/depcomp \
        cfg/install-sh cfg/mkinstalldirs cfg/missing \
        cfg/ltconfig cfg/ltmain.sh \
        cfg/config.sub cfg/config.guess

  find . -name Makefile.in -print | xargs rm
  exit 0
elif test "$1" = "--add"; then
  AUTOMAKE_ADD="--add-missing --gnu --copy"
fi

echo "Checking the installed configuration tools..."

if test -z "`autoconf --version 2>/dev/null | grep \" $AUTOCONF_VER\"`"; then
    echo ""
    echo "You must have autoconf version $AUTOCONF_VER installed to"
    echo "generate configure information and Makefiles for $PROJECT."
    echo ""
    echo "(The Autoconf version we are using is the bleeding edge"
    echo "from the CVS repository.)"
    DIE=true
fi

if test -z "`automake --version 2>/dev/null | grep \" $AUTOMAKE_VER\"`"; then
    echo ""
    echo "You must have automake version $AUTOMAKE_VER installed to"
    echo "generate configure information and Makefiles for $PROJECT."
    echo ""
    echo "(The Automake version we are using is the bleeding edge"
    echo "from the CVS repository.)"
    DIE=true
fi

if test -z "`libtool --version | egrep \"$LIBTOOL_VER\" 2> /dev/null`"; then
    echo
    echo "You must have libtool version $LIBTOOL_VER installed to"
    echo "generate configure information and Makefiles for $PROJECT."
    echo ""
    echo "Get ftp://ftp.gnu.org/pub/gnu/libtool/libtool-1.3.5.tar.gz"
    echo ""
    DIE=true
fi

set $SUBPROJECTNAMES
num=1
for project in $SUBPROJECTS; do
  test -d $project || {
    echo
    echo "Could not find subdirectory '$project'."
    echo "It was probably added after you initially fetched $PROJECT."
    echo "To add the missing module, run 'cvs co $1' from the $PROJECT"
    echo "base directory."
    echo ""
    echo "To do a completely fresh cvs checkout of the whole $PROJECT module,"
    echo "(if all else fails), remove $PROJECT and run:"
    echo "  cvs -z3 -d :pserver:cvs@cvs.sim.no:/export/cvsroot co -P $PROJECT"
    echo ""
    DIE=true
  }
  num=`expr $num + 1`
  shift
done

# abnormal exit?
${DIE=false} && echo "" && echo >&2 "$me: aborting..." && exit 1

# **************************************************************************

# generate aclocal.m4
echo "Running aclocal..."
aclocal -I $MACRODIR

# generate configure
echo "Running autoconf..."
autoconf

# generate config.h.in
echo "Running autoheader..."
( autoheader 3>&1 1>&2 2>&3 | grep -v 'is unchanged$' ) 3>&1 1>&2 2>&3

# generate Makefile.in templates
echo "Running automake..."
( automake $AUTOMAKE_ADD 3>&1 1>&2 2>&3 | grep -v 'directory should not' ) 3>&1 1>&2 2>&3

