#! /bin/sh
# not to be executed - only sourced

GUI="Qt"
lGUI="qt"
uGUI="QT"
WIDGET="QWidget *"
EVENT="QEvent *"
COMPONENTHEADER="Q_OBJECT"

HAVE_RENDERAREA=true
HAVE_EXAMINERVIEWER=true
HAVE_PLANEVIEWER=true
HAVE_WALKVIEWER=false
HAVE_FLYVIEWER=false

export GUI uGUI lGUI
export WIDGET EVENT COMPONENTHEADER
export HAVE_RENDERAREA HAVE_EXAMINERVIEWER
export HAVE_PLANEVIEWER HAVE_WALKVIEWER HAVE_FLYVIEWER

