#! /bin/sh
# **************************************************************************
# soqt-config -- a utility for retrieving configuration information about
# the installed SoQt library.

program="$0"
me=`echo "$0" | sed 's,^.*[/\\],,g'`
wd=`echo "$0" | sed 's,/[^/]*$,,'`
prefix=`cd "$wd"/..; pwd` 

usage="\
Usage: $me [OPTIONS]
Options:
  --alternate=<string>
  --cppflags
  --cxxflags
  --ldflags
  --libs
  --datadir
  --have-feature <featurename>
  --ac-subst <string> | <sourcefile.in>
  --ac-desubst <sourcefile>
  --compile <sourcefile> [<sourcefile>]...
  --link <program> <object> [<object>]...
  --build <program> <sourcefile> [<sourcefile>]...
  --version
  --usage | --help"

alternate=default
for arg
do
  case $arg in
  --alternate=*) alternate=`echo $arg | cut -d= -f2-` ;;
  --debug) alternate=debug ;;
  esac
done

if test -f $prefix/share/Coin/conf/soqt-$alternate.cfg; then
  configfile="$prefix/share/Coin/conf/soqt-$alternate.cfg"
  . $configfile
elif test -f $prefix/share/Coin/conf/soqt-default.cfg; then
  configfile="$prefix/share/Coin/conf/soqt-default.cfg"
  . $configfile
else
  echo >&2 "$me: no default SoQt config available"
  exit 1
fi

while test $# -gt 0
do
  case $1 in
    --usage | --help)  echo "$usage"    ;;
    --version)         echo "$version"  ;;
    --cppflags)        echo "$cppflags" ;;
    --cxxflags)        echo "$cxxflags" ;;
    --ldflags)         echo "$ldflags"  ;;
    --libs)            echo "$libs"     ;;
    --datadir)         echo "$datadir"  ;;
    --have-feature)
      exitcode=1
      eval "test x\${have_$2+set} = xset && exitcode=0"
      exit $exitcode
      ;;
    --ac-subst)
      shift
      if test $# -eq 1; then
        case $1 in
          *\.in)
            echo $me --ac-subst $1
            outfile=`echo $1 | sed -e 's/\.in$//'`
            sedscript=/tmp/ac_subst_$$.sed
            grep "^AC_SUBST_" $configfile \
              | sed -e 's/^AC_SUBST_\([^=]*\)="\([^"]*\)"$/s\/@\1@\/\2\/g;/g' \
              >$sedscript
            sed -f $sedscript <$1 >$outfile
            rm -f $sedscript
            ;;
          *)
            eval "VAL=\${AC_SUBST_$1}"
            echo "$VAL"
            ;;
        esac
      else
        for arg in $@; do
          $program --ac-subst $arg
          retval=$?
          test $retval -ne 0 && exit $retval
        done
      fi
      exit 0
      ;;
    --ac-desubst)
      shift
      echo $me --ac-desubst $1
      outfile="$1.in"
      sedscript=/tmp/ac_subst_$$.sed
      grep "^AC_SUBST_" $configfile \
        | sed -e 's/^AC_SUBST_\([^=]*\)="\([^"]*\)"$/s\/\2\/@\1@\/g;/g' \
        >$sedscript
      sed -f $sedscript <$1 >$outfile
      rm -f $sedscript
      ;;
    --compile)
      shift
      if test $# -eq 1; then
        case $1 in
          *\.in)
            outfile=`echo $1 | sed -e 's/\.in$//'`
            $program --ac-subst $1
            $program --alternate="$alternate" --compile $outfile
            retval=$?
            test $retval -ne 0 && exit $retval
            ;;
          *)
            echo $compiler $CPPFLAGS $cppflags $CXXFLAGS $cxxflags -c $1 \
              | fmt -w76 | sed '2,$ s/^/  /g; $ q; 1,$ s/$/ \\/'
            $compiler \
              $CPPFLAGS $cppflags \
              $CXXFLAGS $cxxflags \
              -c $1
            retval=$?
            test $retval -ne 0 && exit $retval
            ;;
        esac
      else
        for arg in $@; do
          $program --alternate="$alternate" --compile $arg
          retval=$?
          test $retval -ne 0 && exit $retval
        done
      fi
      exit 0
      ;;
    --link)
      shift
      progname=$1
      shift
      echo $compiler $LDFLAGS $ldflags -o $progname $@ $libs $LIBS \
        | fmt -w76 | sed '2,$ s/^/  /g; $ q; 1,$ s/$/ \\/'
      $compiler \
        $LDFLAGS $ldflags \
        -o $progname $@ \
        $libs $LIBS
      retval=$?
      test $retval -ne 0 && exit $retval
      exit 0
      ;;
    --build)
      shift
      progname=$1
      objs=
      extraldflags=
      extralibs=
      shift
      for arg in $@; do
        case $arg in
          *.h.in)
            $program --ac-subst $arg
            ;;
          *.c.in | *.cpp.in | *.cxx.in | *.cc.in)
            outfile=`echo "$arg" | sed -e 's/\.in$//'`
            basename=`echo "$outfile" | sed -e 's/\.[^\.]*$//'`
            $program --ac-subst $arg
            $program --alternate="$alternate" --compile $outfile
            retval=$?
            test $retval -ne 0 && exit $retval
            objfile=`ls $basename.o $basename.obj 2>/dev/null`
            objs="$objs $objfile"
            ;;
          -L*)
            extraldflags="$extraldflags $arg"
            ;;
          -l*)
            extralibs="$extralibs $arg"
            ;;
        esac
      done
      echo $compiler $CPPFLAGS $cppflags $CXXFLAGS $cxxflags \
        $LDFLAGS $ldflags $extraldflags \
        -o $progname $objs $extralibs $libs $LIBS \
        | fmt -w76 | sed '2,$ s/^/  /g; $ q; 1,$ s/$/ \\/'
      $compiler \
        $CPPFLAGS $cppflags \
        $CXXFLAGS $cxxflags \
        $LDFLAGS $ldflags $extraldflags \
        -o $progname $objs \
        $extralibs $libs $LIBS
      retval=$?
      test $retval -ne 0 && exit $retval
      exit 0
      ;;
    # ignore some options
    --alternate=*) ;;
    --debug) ;;
    # args not catched until now are invalid
    *)
      echo >&2 "$me: Invalid option: \"$1\""
      echo >&2 "$usage"
      exit 1
      ;;
  esac
  shift
done

exit 0

